/* Autogenerated by png2wx.pl on Wed Mar 27 14:42:14 2013 */
#ifndef EMBEDDEDIMAGES_H
#define EMBEDDEDIMAGES_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_command;
extern wxBitmap *_img_exit;
extern wxBitmap *_img_help;
extern wxBitmap *_img_logo;
extern wxBitmap *_img_properties;
extern wxBitmap *_img_psy;
extern wxBitmap *_img_refresh;
extern wxBitmap *_img_submenu;
extern wxBitmap *_img_up;
extern wxBitmap *_img_prog_icon;

#endif /* EMBEDDEDIMAGES_H */
