/* Autogenerated by png2wx.pl on Wed Mar 27 16:11:43 2013 */
#ifndef HELPSTRINGS_H
#define HELPSTRINGS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_help_strings(void);

extern wxString *_help_en_html;

#endif /* HELPSTRINGS_H */
